import "./globals.css";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header className="fixed top-0 w-full flex justify-between p-5">
          <Link href="" className="font-bold">Junho's Blog</Link>
          <div className="flex gap-4 text-gray-400">
            <Link href="">Home</Link>
            <Link href="about">about</Link>
            <Link href="posts">posts</Link>
            <Link href="contact">contact</Link>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
